{% set name = "climada-petals" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/climada_petals-{{ version }}.tar.gz
  sha256: a1dc78da2805c21053d92cc9e8fc2d9460eef337beed1dd2cc9c077968aee65b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
    - meson =1.4
    - meson-python =0.18
  run:
    - python >={{ python_min }},<3.13
    - climada =6.1
    - boario >=0.6.2
    - cdsapi =0.7
    - esmpy >=8.4
    - importlib-metadata =7.2
    - libgdal =3.10
    - osm-flex =1.1
    - overpy =0.7
    - pymoo =0.6.1
    - pymrio >=0.4.8
    - rioxarray =0.19
    - ruamel.yaml =0.18
    - scikit-image >0.25
    - xesmf =0.8

test:
  imports:
    - climada_petals
  source_files:
    - climada_petals
  commands:
    - pip check
    - pytest climada_petals/test/test_cropyield_integr.py
  requires:
    - pip =24.0
    - pytest
    - pytest-json-report
    - python {{ python_min }}

about:
  home: https://github.com/CLIMADA-project/climada_petals
  summary: "CLIMADA-Petals: The extension module for CLIMADA (probabilistic natural catastrophe impact model in Python)"
  description: |
    CLIMADA Petals generates different types of hazards and contains more specialized
    applications than the CLIMADA Core module.
    CLIMADA (CLIMate ADAptation) is a free and open-source software framework
    for climate risk assessment and adaptation option appraisal. Designed by a
    large scientific community, it helps reasearchers, policymakers, and
    businesses analyse the impacts of natural hazards and explore adaptation
    strategies.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-petals.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - emanuel-schmid
    - peanutfun
